/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fescfafic.imagempdi.classes;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Gutemberg
 */
public class Imagem extends javax.swing.JFrame {
    
    private BufferedImage img;
    
    /**
     * Creates new form Imagem
     */
    public Imagem() {
        initComponents();
        //exibirImagem();
        //exibirRgb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        grayscaleRed = new javax.swing.JMenuItem();
        grayscaleGreen = new javax.swing.JMenuItem();
        grayscaleBlue = new javax.swing.JMenuItem();
        grayscaleMedia = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        bandaSeparadaRed = new javax.swing.JMenuItem();
        bandaSeparadaGreen = new javax.swing.JMenuItem();
        bandaSeparadaBlue = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Processamento Digital de Imagens");
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Abra uma nova imagem em: Imagem > Abrir");

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Desenvolvido por: Gutemberg Ferreira Dantas - 4° Período - Ciência da Computação");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jMenu2.setText("Imagem");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenu1.setText("Editar");

        jMenuItem3.setText("Pintar 1° pixel");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenu3.setText("Tons de Cinza");

        grayscaleRed.setText("Red");
        grayscaleRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grayscaleRedActionPerformed(evt);
            }
        });
        jMenu3.add(grayscaleRed);

        grayscaleGreen.setText("Green");
        grayscaleGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grayscaleGreenActionPerformed(evt);
            }
        });
        jMenu3.add(grayscaleGreen);

        grayscaleBlue.setText("Blue");
        grayscaleBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grayscaleBlueActionPerformed(evt);
            }
        });
        jMenu3.add(grayscaleBlue);

        grayscaleMedia.setText("Media");
        grayscaleMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grayscaleMediaActionPerformed(evt);
            }
        });
        jMenu3.add(grayscaleMedia);

        jMenu1.add(jMenu3);

        jMenu4.setText("Banda de Cores");

        bandaSeparadaRed.setText("Red");
        bandaSeparadaRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bandaSeparadaRedActionPerformed(evt);
            }
        });
        jMenu4.add(bandaSeparadaRed);

        bandaSeparadaGreen.setText("Green");
        bandaSeparadaGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bandaSeparadaGreenActionPerformed(evt);
            }
        });
        jMenu4.add(bandaSeparadaGreen);

        bandaSeparadaBlue.setText("Blue");
        bandaSeparadaBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bandaSeparadaBlueActionPerformed(evt);
            }
        });
        jMenu4.add(bandaSeparadaBlue);

        jMenu1.add(jMenu4);

        jMenu2.add(jMenu1);

        jMenuItem4.setText("Salvar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem2.setText("Excluir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grayscaleRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grayscaleRedActionPerformed
        for(int x = 0; x < img.getWidth(); x++){
            for(int y = 0; y < img.getHeight(); y++){
                int red = new Color(img.getRGB(x, y)).getRed();
                Color escalaRed = new Color(red, red, red);
                img.setRGB(x, y, escalaRed.getRGB());
            }
        }
        jLabel1.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_grayscaleRedActionPerformed

    private void grayscaleGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grayscaleGreenActionPerformed
        for(int x = 0; x < img.getWidth(); x++){
            for(int y = 0; y < img.getHeight(); y++){
                int green = new Color(img.getRGB(x, y)).getGreen();
                Color escalaGreen = new Color(green, green, green);
                img.setRGB(x, y, escalaGreen.getRGB());
            }
        }
        jLabel1.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_grayscaleGreenActionPerformed

    private void grayscaleBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grayscaleBlueActionPerformed
        for(int x = 0; x < img.getWidth(); x++){
            for(int y = 0; y < img.getHeight(); y++){
                int blue = new Color(img.getRGB(x, y)).getBlue();
                Color escalaBlue = new Color(blue, blue, blue);
                img.setRGB(x, y, escalaBlue.getRGB());
            }
        }
        jLabel1.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_grayscaleBlueActionPerformed

    private void grayscaleMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grayscaleMediaActionPerformed
        for(int x = 0; x < img.getWidth(); x++){
            for(int y = 0; y < img.getHeight(); y++){
                int red = new Color(img.getRGB(x, y)).getRed();
                int green = new Color(img.getRGB(x, y)).getGreen();
                int blue = new Color(img.getRGB(x, y)).getBlue();
                int media = (red + green + blue) / 3;
                Color escalaMedia = new Color(media, media, media);
                img.setRGB(x, y, escalaMedia.getRGB());
            }
        }
        jLabel1.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_grayscaleMediaActionPerformed

    private void bandaSeparadaRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bandaSeparadaRedActionPerformed
        //BufferedImage imgRed = abrirImagem();
        for(int x = 0; x < img.getWidth(); x++){
            for(int y = 0; y < img.getHeight(); y++){
                int red = new Color(img.getRGB(x, y)).getRed();
                Color cor = new Color(red, 0, 0);
                img.setRGB(x, y, cor.getRGB());
            }
        }
        jLabel1.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_bandaSeparadaRedActionPerformed

    private void bandaSeparadaGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bandaSeparadaGreenActionPerformed
        //BufferedImage imgGreen = abrirImagem();
        for(int x = 0; x < img.getWidth(); x++){
            for(int y = 0; y < img.getHeight(); y++){
                int green = new Color(img.getRGB(x, y)).getGreen();
                Color cor = new Color(0, green, 0);
                img.setRGB(x, y, cor.getRGB());
            }
        }
        jLabel1.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_bandaSeparadaGreenActionPerformed

    private void bandaSeparadaBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bandaSeparadaBlueActionPerformed
        //BufferedImage imgBlue = abrirImagem();
        for(int x = 0; x < img.getWidth(); x++){
            for(int y = 0; y < img.getHeight(); y++){
                int blue = new Color(img.getRGB(x, y)).getBlue();
                Color cor = new Color(0, 0, blue);
                img.setRGB(x, y, cor.getRGB());
            }
        }
        jLabel1.setIcon(new ImageIcon(img));
    }//GEN-LAST:event_bandaSeparadaBlueActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        exibirImagem();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jLabel1.setIcon(null);
        jLabel1.setText("Abra uma nova imagem em: Imagem > Abrir");
        jLabel2.setText("");
        img = null;
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        pintarPixel();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JFileChooser salvar = new JFileChooser();
        salvar.setFileFilter(new FileNameExtensionFilter(".jpg", "jpg"));
        salvar.setAcceptAllFileFilterUsed(false);
        int res = salvar.showSaveDialog(null);
        if(res == JFileChooser.APPROVE_OPTION){
            try {
                String caminho = String.valueOf(salvar.getSelectedFile());
                ImageIO.write(img, "jpg", new File(caminho + salvar.getFileFilter().getDescription()));
            } catch (IOException ex) {
                Logger.getLogger(Imagem.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        JOptionPane.showMessageDialog(null, "Foto salva com sucesso!");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private String escolherImagem(){
        JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i = file.showOpenDialog(null);
        if(i == 0){
            File f = file.getSelectedFile();
            return f.getPath();
        }
        else if(i == 1){
            return null;
        }
        return null;
    }
    
    private BufferedImage abrirImagem(){
        try {
            img = ImageIO.read(new File(escolherImagem()));
            return img;
        } catch (IOException ex) {
            Logger.getLogger(Imagem.class.getName())
                    .log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    private void exibirImagem(){
        img = abrirImagem();
        
        ImageIcon i = new ImageIcon(img);
        jLabel1.setIcon(i);
        jLabel1.setText("");
        
        int pixels = img.getWidth() * img.getHeight();
        jLabel2.setText("Quantidade de pixels: " + pixels);
    }
    
    public void exibirRgb(){
        Color cor = new Color(img.getRGB(0, 0));
        System.out.println("Vermelho: " + cor.getRed() + 
                " Verde: " + cor.getGreen() + " Azul: " + cor.getBlue());
    }
    
    public void pintarPixel(){
        Color cor = new Color(255, 255, 255);
        img.setRGB(0, 0, cor.getRGB());
        JOptionPane.showMessageDialog(rootPane,
                "Primeiro pixel da imagem pintado com sucesso!");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Imagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Imagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Imagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Imagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Imagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bandaSeparadaBlue;
    private javax.swing.JMenuItem bandaSeparadaGreen;
    private javax.swing.JMenuItem bandaSeparadaRed;
    private javax.swing.JMenuItem grayscaleBlue;
    private javax.swing.JMenuItem grayscaleGreen;
    private javax.swing.JMenuItem grayscaleMedia;
    private javax.swing.JMenuItem grayscaleRed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
