/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacePDI;


import classes.Manipulacao;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author COMPUTER
 */
public class Interface extends javax.swing.JFrame {
    
    Manipulacao manipulacao = new Manipulacao();    
    
    private BufferedImage imagem = null;
    private BufferedImage editado = null;
    private boolean abrir = false;
    private boolean testModified = false;  
    private boolean testSaveDelete = false;
    
    public Interface() throws IOException {
        initComponents();
    }
    
    public void exibirImagemOriginal(){
        ExibirImagem1.setIcon(new ImageIcon(imagem));
        
        String pixel =  Integer.toString(imagem.getWidth() * imagem.getHeight()) ;
        text1.setText(String.valueOf("                                                                                        "
                + "                            Quantidade de pixels: " + pixel +  "                  "
                        + "Desenvolvido por Bruno - 4º período - Ciência da Computação"));
    }
    
    public void exibirImagemEditado(){
        ExibirImagem2.setIcon(new ImageIcon(editado));
    }
    
    public void excluirText(){
        ExibirImagem1.setText(String.valueOf(""));
        ExibirImagem2.setText(String.valueOf(""));
    }  
    
    private void mensagenMensagens1(){
        JOptionPane.showMessageDialog(null, "Erro: Necessario exibir a imagem!!!");
    }  
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        scrollPane1 = new java.awt.ScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        ExibirImagem1 = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();
        ExibirImagem2 = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();
        text3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        Abrir = new javax.swing.JRadioButtonMenuItem();
        Salvar = new javax.swing.JRadioButtonMenuItem();
        Excluir = new javax.swing.JRadioButtonMenuItem();
        jMenu5 = new javax.swing.JMenu();
        BandasSeparadas = new javax.swing.JMenu();
        BandasSeparadasRed = new javax.swing.JRadioButtonMenuItem();
        BandasSeparadasGreen = new javax.swing.JRadioButtonMenuItem();
        BandasSeparadasBlue = new javax.swing.JRadioButtonMenuItem();
        TonsCinza = new javax.swing.JMenu();
        GrayscaleRed = new javax.swing.JRadioButtonMenuItem();
        GrayscaleGreen = new javax.swing.JRadioButtonMenuItem();
        GrayscaleBlue = new javax.swing.JRadioButtonMenuItem();
        GrayscaleMedia = new javax.swing.JRadioButtonMenuItem();
        jMenu7 = new javax.swing.JMenu();
        AditivoRGB = new javax.swing.JRadioButtonMenuItem();
        AditivoY = new javax.swing.JRadioButtonMenuItem();
        MultBrilhoRGB = new javax.swing.JRadioButtonMenuItem();
        MultBrilhoY = new javax.swing.JRadioButtonMenuItem();
        jMenu8 = new javax.swing.JMenu();
        Negativo = new javax.swing.JRadioButtonMenuItem();
        NegativoY = new javax.swing.JRadioButtonMenuItem();
        Editar = new javax.swing.JMenu();
        Limiarizacao = new javax.swing.JRadioButtonMenuItem();
        yiqToRGB = new javax.swing.JRadioButtonMenuItem();
        jMenu9 = new javax.swing.JMenu();
        FiltroMedia = new javax.swing.JRadioButtonMenuItem();
        FiltroMediana = new javax.swing.JRadioButtonMenuItem();
        FiltroModa = new javax.swing.JRadioButtonMenuItem();
        FiltroMediaColorido = new javax.swing.JRadioButtonMenuItem();
        FiltroMedianaColorido = new javax.swing.JRadioButtonMenuItem();
        convolução = new javax.swing.JRadioButtonMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setForeground(new java.awt.Color(102, 153, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Projeto PDI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(592, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(578, 578, 578))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        ExibirImagem1.setText("                                                                      OBS: Necessario exibir a imagem!!!");
        ExibirImagem1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ExibirImagem2.setText("                                                                      OBS: Necessario exibir a imagem!!!");
        ExibirImagem2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        text1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        text3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(634, 634, 634)
                        .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ExibirImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExibirImagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(ExibirImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(ExibirImagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(text2))
        );

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/bullet_wrench.png"))); // NOI18N
        jMenu6.setText("Opções");

        Abrir.setSelected(true);
        Abrir.setText("Abrir");
        Abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/user_go.png"))); // NOI18N
        Abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirActionPerformed(evt);
            }
        });
        jMenu6.add(Abrir);

        Salvar.setSelected(true);
        Salvar.setText("Salvar");
        Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/drive_user.png"))); // NOI18N
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });
        jMenu6.add(Salvar);

        Excluir.setSelected(true);
        Excluir.setText("Excluir");
        Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/user_delete.png"))); // NOI18N
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        jMenu6.add(Excluir);

        jMenuBar1.add(jMenu6);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/image.png"))); // NOI18N
        jMenu5.setText("Imagem");

        BandasSeparadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/image_edit.png"))); // NOI18N
        BandasSeparadas.setText("Bandas Separadas");

        BandasSeparadasRed.setSelected(true);
        BandasSeparadasRed.setText("Red");
        BandasSeparadasRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/user_red.png"))); // NOI18N
        BandasSeparadasRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BandasSeparadasRedActionPerformed(evt);
            }
        });
        BandasSeparadas.add(BandasSeparadasRed);

        BandasSeparadasGreen.setSelected(true);
        BandasSeparadasGreen.setText("Green");
        BandasSeparadasGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/user_green.png"))); // NOI18N
        BandasSeparadasGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BandasSeparadasGreenActionPerformed(evt);
            }
        });
        BandasSeparadas.add(BandasSeparadasGreen);

        BandasSeparadasBlue.setSelected(true);
        BandasSeparadasBlue.setText("Blue");
        BandasSeparadasBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/user_suit.png"))); // NOI18N
        BandasSeparadasBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BandasSeparadasBlueActionPerformed(evt);
            }
        });
        BandasSeparadas.add(BandasSeparadasBlue);

        jMenu5.add(BandasSeparadas);

        TonsCinza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/image_edit.png"))); // NOI18N
        TonsCinza.setText("Tons Cinza");

        GrayscaleRed.setSelected(true);
        GrayscaleRed.setText("Red");
        GrayscaleRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/user_red.png"))); // NOI18N
        GrayscaleRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrayscaleRedActionPerformed(evt);
            }
        });
        TonsCinza.add(GrayscaleRed);

        GrayscaleGreen.setSelected(true);
        GrayscaleGreen.setText("Green");
        GrayscaleGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/user_green.png"))); // NOI18N
        GrayscaleGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrayscaleGreenActionPerformed(evt);
            }
        });
        TonsCinza.add(GrayscaleGreen);

        GrayscaleBlue.setSelected(true);
        GrayscaleBlue.setText("Blue");
        GrayscaleBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/user_suit.png"))); // NOI18N
        GrayscaleBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrayscaleBlueActionPerformed(evt);
            }
        });
        TonsCinza.add(GrayscaleBlue);

        GrayscaleMedia.setSelected(true);
        GrayscaleMedia.setText("Media");
        GrayscaleMedia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/user_gray.png"))); // NOI18N
        GrayscaleMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrayscaleMediaActionPerformed(evt);
            }
        });
        TonsCinza.add(GrayscaleMedia);

        jMenu5.add(TonsCinza);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/image_edit.png"))); // NOI18N
        jMenu7.setText("Brilho");

        AditivoRGB.setSelected(true);
        AditivoRGB.setText("Aditivo em RGB");
        AditivoRGB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/page_white_width.png"))); // NOI18N
        AditivoRGB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AditivoRGBActionPerformed(evt);
            }
        });
        jMenu7.add(AditivoRGB);

        AditivoY.setSelected(true);
        AditivoY.setText("Aditivo em  Y");
        AditivoY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/page_white_width.png"))); // NOI18N
        AditivoY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AditivoYActionPerformed(evt);
            }
        });
        jMenu7.add(AditivoY);

        MultBrilhoRGB.setSelected(true);
        MultBrilhoRGB.setText("Multiplicativo em RGB");
        MultBrilhoRGB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/page_white_width.png"))); // NOI18N
        MultBrilhoRGB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultBrilhoRGBActionPerformed(evt);
            }
        });
        jMenu7.add(MultBrilhoRGB);

        MultBrilhoY.setSelected(true);
        MultBrilhoY.setText("Multiplicativo em Y");
        MultBrilhoY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/page_white_width.png"))); // NOI18N
        MultBrilhoY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultBrilhoYActionPerformed(evt);
            }
        });
        jMenu7.add(MultBrilhoY);

        jMenu5.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/image_edit.png"))); // NOI18N
        jMenu8.setText("Negativo");

        Negativo.setSelected(true);
        Negativo.setText("Negativo em RGB");
        Negativo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/page_white_width.png"))); // NOI18N
        Negativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NegativoActionPerformed(evt);
            }
        });
        jMenu8.add(Negativo);

        NegativoY.setSelected(true);
        NegativoY.setText("Negativo em Y");
        NegativoY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/page_white_width.png"))); // NOI18N
        NegativoY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NegativoYActionPerformed(evt);
            }
        });
        jMenu8.add(NegativoY);

        jMenu5.add(jMenu8);

        Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/image_edit.png"))); // NOI18N
        Editar.setText("Variado");

        Limiarizacao.setSelected(true);
        Limiarizacao.setText("Limiarização");
        Limiarizacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/page_white_width.png"))); // NOI18N
        Limiarizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimiarizacaoActionPerformed(evt);
            }
        });
        Editar.add(Limiarizacao);

        yiqToRGB.setSelected(true);
        yiqToRGB.setText("yiqToRGB");
        yiqToRGB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/page_white_width.png"))); // NOI18N
        yiqToRGB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yiqToRGBActionPerformed(evt);
            }
        });
        Editar.add(yiqToRGB);

        jMenu5.add(Editar);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/image_edit.png"))); // NOI18N
        jMenu9.setText("Filtro Passa Baixa");

        FiltroMedia.setSelected(true);
        FiltroMedia.setText("Filtro Media");
        FiltroMedia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/page_white_width.png"))); // NOI18N
        FiltroMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltroMediaActionPerformed(evt);
            }
        });
        jMenu9.add(FiltroMedia);

        FiltroMediana.setSelected(true);
        FiltroMediana.setText("Filtro Mediana");
        FiltroMediana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/page_white_width.png"))); // NOI18N
        FiltroMediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltroMedianaActionPerformed(evt);
            }
        });
        jMenu9.add(FiltroMediana);

        FiltroModa.setSelected(true);
        FiltroModa.setText("Filtro Moda");
        FiltroModa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/page_white_width.png"))); // NOI18N
        FiltroModa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltroModaActionPerformed(evt);
            }
        });
        jMenu9.add(FiltroModa);

        FiltroMediaColorido.setSelected(true);
        FiltroMediaColorido.setText("Filtro Media Colorido");
        FiltroMediaColorido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/page_white_width.png"))); // NOI18N
        FiltroMediaColorido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltroMediaColoridoActionPerformed(evt);
            }
        });
        jMenu9.add(FiltroMediaColorido);

        FiltroMedianaColorido.setSelected(true);
        FiltroMedianaColorido.setText("Filtro Mediana Colorido");
        FiltroMedianaColorido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/page_white_width.png"))); // NOI18N
        FiltroMedianaColorido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltroMedianaColoridoActionPerformed(evt);
            }
        });
        jMenu9.add(FiltroMedianaColorido);

        convolução.setSelected(true);
        convolução.setText("Convolução");
        convolução.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/page_white_width.png"))); // NOI18N
        convolução.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convoluçãoActionPerformed(evt);
            }
        });
        jMenu9.add(convolução);

        jMenu5.add(jMenu9);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BandasSeparadasRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BandasSeparadasRedActionPerformed
        if (abrir) {
            testModified = true; 
            
            editado = manipulacao.bandasSeparadasRed(imagem);
            
            exibirImagemEditado();
            excluirText();
            text3.setText(String.valueOf("              Bandas Separadas RED"));
        }
        else{
            mensagenMensagens1();
        } 
    }//GEN-LAST:event_BandasSeparadasRedActionPerformed

    private void BandasSeparadasGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BandasSeparadasGreenActionPerformed
        if (abrir) {
            testModified = true; 
            
            editado = manipulacao.bandasSeparadasGreen(imagem);
            
            exibirImagemEditado();
            excluirText();
            text3.setText(String.valueOf("         Bandas Separadas GREEN"));
        }
        else{
            mensagenMensagens1();
        }
    }//GEN-LAST:event_BandasSeparadasGreenActionPerformed

    private void BandasSeparadasBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BandasSeparadasBlueActionPerformed
        if (abrir) {
            testModified = true; 
            
            editado = manipulacao.bandasSeparadasBlue(imagem);
            
            exibirImagemEditado();
            excluirText();
            text3.setText(String.valueOf("              Bandas Separadas BLUE"));
        }
        else{
            mensagenMensagens1();
        }
    }//GEN-LAST:event_BandasSeparadasBlueActionPerformed

    private void GrayscaleRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrayscaleRedActionPerformed
        if (abrir) {
            testModified = true; 
            
            editado = manipulacao.grayscaleRed(imagem); 
            
            exibirImagemEditado();
            excluirText();
            text3.setText(String.valueOf("                   Grayscale RED"));
        }
        else{
            mensagenMensagens1();
        }  
    }//GEN-LAST:event_GrayscaleRedActionPerformed

    private void GrayscaleGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrayscaleGreenActionPerformed
        if (abrir) {
            testModified = true; 
            
            editado = manipulacao.grayscaleGreen(imagem);
            
            exibirImagemEditado();
            excluirText();
            text3.setText(String.valueOf("                Grayscale GREEN"));
        }
        else{
            mensagenMensagens1();
        }

    }//GEN-LAST:event_GrayscaleGreenActionPerformed

    private void GrayscaleBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrayscaleBlueActionPerformed
        if (abrir) {
            testModified = true; 
            
            editado = manipulacao.grayscaleBlue(imagem);
            
            exibirImagemEditado();
            excluirText();
            text3.setText(String.valueOf("                   Grayscale BLUE"));
        }
        else{
            mensagenMensagens1();
        } 
    }//GEN-LAST:event_GrayscaleBlueActionPerformed

    private void GrayscaleMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrayscaleMediaActionPerformed
        if (abrir) {
            testModified = true; 
            
            editado = manipulacao.grayscaleMedia(imagem);
            
            exibirImagemEditado();
            excluirText();
            text3.setText(String.valueOf("                   Grayscale MÉDIA"));
        }
        else{
            mensagenMensagens1();
        }
    }//GEN-LAST:event_GrayscaleMediaActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        if (testSaveDelete) {
            abrir = false;
            testSaveDelete = false;
            
            ExibirImagem1.setIcon(new ImageIcon(""));
            ExibirImagem2.setIcon(new ImageIcon(""));
            
            ExibirImagem1.setText(String.valueOf("                                                                      "
                + "OBS: Necessario abrir a imagem!!!"));
            
            text1.setText(String.valueOf(""));
            text3.setText(String.valueOf(""));
            
            ExibirImagem2.setText(String.valueOf("                                                                      "
                + "OBS: Necessario abrir a imagem!!!"));
        }
        else{
            mensagenMensagens1();
        }
    }//GEN-LAST:event_ExcluirActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
        if (testSaveDelete) {
            if (testModified) {
                manipulacao.salvar(editado);
                JOptionPane.showMessageDialog(null, "Imagem salva com sucesso!!!");
            }
            else{
                JOptionPane.showMessageDialog(null, "Erro: Necessario Editar a imagem!!!");
            }           
        }
        else{
            mensagenMensagens1();
        }
    }//GEN-LAST:event_SalvarActionPerformed

    private void AbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirActionPerformed
        abrir = true;
        
        try {
            imagem = ImageIO.read(new File(manipulacao.escolherImagem()));
        } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName())
                    .log(Level.SEVERE, null, ex);
        }
        
        if (imagem != null) {
            testSaveDelete = true;            
            exibirImagemOriginal();
            
            ExibirImagem2.setIcon(new ImageIcon(""));
            ExibirImagem1.setText(String.valueOf(""));
            ExibirImagem2.setText(String.valueOf("                                                                   "
                    + "OBS: Manipulação da Imagem Liberado!!!"));
            text3.setText(String.valueOf(""));
        }
    }//GEN-LAST:event_AbrirActionPerformed

    private void LimiarizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimiarizacaoActionPerformed
        if (abrir) {
            testModified = true;
            
            String limiarizacao = JOptionPane.showInputDialog("OBS: Números interos!!!"+ "\nEX: 128; 120..." + "\nInforme o valor: " );
            text3.setText(String.valueOf("              Valor da limiarização: " + limiarizacao));
            
            editado = manipulacao.limiarizacao(imagem, Integer.parseInt(limiarizacao));
            
            exibirImagemEditado();            
            excluirText();
        }
        else{
            mensagenMensagens1();
        }
    }//GEN-LAST:event_LimiarizacaoActionPerformed

    private void NegativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NegativoActionPerformed
        if (abrir) {
            testModified = true;
            
            editado = manipulacao.negativo(imagem);
            exibirImagemEditado();
            
            excluirText();
            text3.setText(String.valueOf("                   Negativo em RGB"));
        }else{
            mensagenMensagens1();
        }
    }//GEN-LAST:event_NegativoActionPerformed

    private void yiqToRGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yiqToRGBActionPerformed
        if (abrir) {           
            testModified = true;                
            double[][][] matriz = manipulacao.rgbToYIQ(imagem);

            editado = manipulacao.yiqToRGB(matriz, imagem);

            exibirImagemEditado();
            excluirText();
            text3.setText(String.valueOf("                        YIQ para RGB"));
        }else{
            mensagenMensagens1();
        }
    }//GEN-LAST:event_yiqToRGBActionPerformed

    private void NegativoYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NegativoYActionPerformed
        if (abrir) {            
            testModified = true;
            
            editado = manipulacao.negativoY(imagem);

            exibirImagemEditado();
            excluirText();
            text3.setText(String.valueOf("                   Negativo em Y"));         
        }else{
            mensagenMensagens1();
        }
    }//GEN-LAST:event_NegativoYActionPerformed

    private void AditivoRGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AditivoRGBActionPerformed
        if (abrir) {            
            testModified = true;
            
            String brilho = JOptionPane.showInputDialog("OBS: Números interos!!!"+ "\nEX: 100; 120..." + "\nInforme o valor: ");
            text3.setText(String.valueOf("            Aditivo em RGB: " + brilho));
            
            editado = manipulacao.aditivoRGB(imagem, Integer.parseInt(brilho));

            exibirImagemEditado();
            excluirText();            
        }else{
            mensagenMensagens1();
        }
    }//GEN-LAST:event_AditivoRGBActionPerformed

    private void AditivoYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AditivoYActionPerformed
        if (abrir) {            
            testModified = true;
            
            String brilho = JOptionPane.showInputDialog("OBS: Números interos!!!"+ "\nEX: 100; 110..." + "\nInforme o valor: ");
            text3.setText(String.valueOf("            Aditivo em Y: " + brilho));
            
            editado = manipulacao.aditivoY(imagem, Integer.parseInt(brilho));

            exibirImagemEditado();
            excluirText();            
        }else{
            mensagenMensagens1();
        }
    }//GEN-LAST:event_AditivoYActionPerformed

    private void MultBrilhoRGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultBrilhoRGBActionPerformed
        if (abrir) {            
            testModified = true;
            
            String brilho = JOptionPane.showInputDialog("OBS: Aceita números ponto flutuantes!!!"+ "\nEX: 0.5; 1.0; 1.1..." + "\nInforme o valor: ");
            text3.setText(String.valueOf("        Multiplicativo em RGB: " + brilho));
            
            editado = manipulacao.multBrilhoRGB(imagem, Double.parseDouble(brilho));

            exibirImagemEditado();
            excluirText();            
        }else{
            mensagenMensagens1();
        }
    }//GEN-LAST:event_MultBrilhoRGBActionPerformed

    private void MultBrilhoYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultBrilhoYActionPerformed
        if (abrir) {            
            testModified = true;
            
            String brilho = JOptionPane.showInputDialog("OBS: Aceita números ponto flutuantes!!!"+ "\nEX: 0.5; 1.0; 1.1" + "\nInforme o valor: ");
            text3.setText(String.valueOf("            Multiplicativo em Y: " + brilho));
            
            editado = manipulacao.multBrilhoY(imagem, Double.parseDouble(brilho));

            exibirImagemEditado();
            excluirText();            
        }else{
            mensagenMensagens1();
        }
    }//GEN-LAST:event_MultBrilhoYActionPerformed

    private void FiltroMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltroMediaActionPerformed
        if (abrir) {            
            testModified = true;
            
            String media = JOptionPane.showInputDialog("OBS: Números impares!!!"+ "\nEX: 3; 5; 7..." + "\nInforme o valor: ");
            text3.setText(String.valueOf("              Suavização Media: " + media+ "x" + media));            
            
            editado = manipulacao.filtroMedia(imagem, Integer.parseInt(media));

            exibirImagemEditado();
            excluirText();  
        }else{
            mensagenMensagens1();
        }
    }//GEN-LAST:event_FiltroMediaActionPerformed

    private void FiltroMedianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltroMedianaActionPerformed
        if (abrir) {            
            testModified = true;
            
            String mediana = JOptionPane.showInputDialog("OBS: Números impares!!!"+ "\nEX: 3; 5..." + "\nInforme o valor: ");
            text3.setText(String.valueOf("              Suavização Mediana: " + mediana+ "x" + mediana));
            
            editado = manipulacao.filtroMediana(imagem, Integer.parseInt(mediana));

            exibirImagemEditado();
            excluirText();            
        }else{
            mensagenMensagens1();
        }
    }//GEN-LAST:event_FiltroMedianaActionPerformed

    private void FiltroModaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltroModaActionPerformed
        if (abrir) {
            testModified = true;

            String moda = JOptionPane.showInputDialog("OBS: Números impares!!!"+ "\nEX: 3; 5..." + "\nInforme o valor: ");
            text3.setText(String.valueOf("              Suavização Moda: " + moda+ "x" + moda));

            editado = manipulacao.filtroModa(imagem, Integer.parseInt(moda));

            exibirImagemEditado();
            excluirText();
        }else{
            mensagenMensagens1();
        }
    }//GEN-LAST:event_FiltroModaActionPerformed

    private void FiltroMediaColoridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltroMediaColoridoActionPerformed
        if (abrir) {            
            testModified = true;
            
            String media = JOptionPane.showInputDialog("OBS: Números impares!!!"+ "\nEX: 3; 5; 7..." + "\nInforme o valor: ");
            text3.setText(String.valueOf("              Suavização Media: " + media+ "x" + media));            
            
            editado = manipulacao.filtroMediaColorido(imagem, Integer.parseInt(media));

            exibirImagemEditado();
            excluirText();  
        }else{
            mensagenMensagens1();
        }
    }//GEN-LAST:event_FiltroMediaColoridoActionPerformed

    private void FiltroMedianaColoridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltroMedianaColoridoActionPerformed
        if (abrir) {            
            testModified = true;
            
            String mediana = JOptionPane.showInputDialog("OBS: Números impares!!!"+ "\nEX: 3; 5..." + "\nInforme o valor: ");
            text3.setText(String.valueOf("              Suavização Mediana: " + mediana+ "x" + mediana));
            
            editado = manipulacao.filtroMedianaColorido(imagem, Integer.parseInt(mediana));

            exibirImagemEditado();
            excluirText();            
        }else{
            mensagenMensagens1();
        }
    }//GEN-LAST:event_FiltroMedianaColoridoActionPerformed

    private void convoluçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convoluçãoActionPerformed
        if (abrir) {            
            testModified = true;

            text3.setText(String.valueOf("              Convolução"));
            
            int [] matriz = {1,1,1,1,1,1,1,1,1};
            editado = manipulacao.convolucao(matriz, imagem, 3);

            exibirImagemEditado();
            excluirText();            
        }else{
            mensagenMensagens1();
        }
    }//GEN-LAST:event_convoluçãoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Interface().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem Abrir;
    private javax.swing.JRadioButtonMenuItem AditivoRGB;
    private javax.swing.JRadioButtonMenuItem AditivoY;
    private javax.swing.JMenu BandasSeparadas;
    private javax.swing.JRadioButtonMenuItem BandasSeparadasBlue;
    private javax.swing.JRadioButtonMenuItem BandasSeparadasGreen;
    private javax.swing.JRadioButtonMenuItem BandasSeparadasRed;
    private javax.swing.JMenu Editar;
    private javax.swing.JRadioButtonMenuItem Excluir;
    private javax.swing.JLabel ExibirImagem1;
    private javax.swing.JLabel ExibirImagem2;
    private javax.swing.JRadioButtonMenuItem FiltroMedia;
    private javax.swing.JRadioButtonMenuItem FiltroMediaColorido;
    private javax.swing.JRadioButtonMenuItem FiltroMediana;
    private javax.swing.JRadioButtonMenuItem FiltroMedianaColorido;
    private javax.swing.JRadioButtonMenuItem FiltroModa;
    private javax.swing.JRadioButtonMenuItem GrayscaleBlue;
    private javax.swing.JRadioButtonMenuItem GrayscaleGreen;
    private javax.swing.JRadioButtonMenuItem GrayscaleMedia;
    private javax.swing.JRadioButtonMenuItem GrayscaleRed;
    private javax.swing.JRadioButtonMenuItem Limiarizacao;
    private javax.swing.JRadioButtonMenuItem MultBrilhoRGB;
    private javax.swing.JRadioButtonMenuItem MultBrilhoY;
    private javax.swing.JRadioButtonMenuItem Negativo;
    private javax.swing.JRadioButtonMenuItem NegativoY;
    private javax.swing.JRadioButtonMenuItem Salvar;
    private javax.swing.JMenu TonsCinza;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButtonMenuItem convolução;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JSplitPane jSplitPane1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    private javax.swing.JRadioButtonMenuItem yiqToRGB;
    // End of variables declaration//GEN-END:variables
}
